# Generated by Django 5.2 on 2025-04-23 02:57

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField()),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='paises', variations={'normal': (800, 600), 'thumb': (300, 200)})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Membro da equipe'),
        ),
    ]
