# Generated by Django 5.2 on 2025-04-26 16:56

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pais_alter_customusuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='paises', variations={'normal': (600, 400), 'thumb': (200, 100)}),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagemCdd', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='paises', variations={'normal': (150, 100)})),
                ('populacao', models.CharField()),
                ('idh', models.DecimalField(decimal_places=5, max_digits=5)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade', to='core.pais')),
            ],
        ),
    ]
