# Generated by Django 5.2 on 2025-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pais_imagem_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='idh',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
