# Generated by Django 5.2 on 2025-04-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cidade_idh'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='descricao',
            field=models.CharField(default='no descriptipn', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='populacao',
            field=models.CharField(max_length=19),
        ),
    ]
