# Generated by Django 5.2 on 2025-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cidade_descricao_alter_cidade_populacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.CharField(),
        ),
    ]
