# Generated by Django 5.2 on 2025-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cidade_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.TextField(),
        ),
    ]
