# Generated by Django 5.2 on 2025-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cidade_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
