# Generated by Django 5.2 on 2025-05-06 02:53

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cidade_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='paises', variations={'normal': (600, 600), 'thumb': (200, 100)}),
        ),
    ]
